# Generated by Django 4.0.2 on 2022-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todo_uid_alter_todo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_created',
            field=models.DateField(default='2022-03-12'),
        ),
    ]
