version: '3.7'
services:
  db:
    image: postgres:14.2
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: todo_project
#  adminer:
#    image: adminer:4.8.1-standalone
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
  backend:
    build:
      context: 2_step_2 for test django and migrations
    ports:
      - 8080:8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py create_data
      && python manage.py runserver 0.0.0.0:8080
      "
    depends_on:
      - db
