# Generated by Django 4.0.2 on 2022-04-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='username',
            new_name='user_ptk',
        ),
    ]
