# Generated by Django 4.0.2 on 2022-04-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_author_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_staff',
        ),
    ]
