# Generated by Django 4.0.4 on 2022-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_created',
            field=models.DateField(default='2022-04-26'),
        ),
    ]
