# Generated by Django 4.0.2 on 2022-04-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_author_username'),
        ('todoapp', '0002_alter_todo_is_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
            preserve_default=False,
        ),
    ]
