# Generated by Django 4.0.2 on 2022-04-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_created',
            field=models.DateField(default='2022-04-09'),
        ),
    ]
