# Generated by Django 4.0.2 on 2022-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_todo_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_created',
            field=models.DateField(default='2022-04-10'),
        ),
    ]
