# Generated by Django 4.0.3 on 2022-04-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_remove_project_authors_project_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_created',
            field=models.DateField(default='2022-04-17'),
        ),
    ]
