# Generated by Django 4.0.3 on 2022-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_project_is_active_alter_todo_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_created',
            field=models.DateField(default='2022-04-19'),
        ),
    ]
