# Generated by Django 4.0.2 on 2022-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_username_author_user_ptk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_ptk',
            new_name='username',
        ),
    ]
