# Generated by Django 4.0.2 on 2022-04-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_first_name_alter_author_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
